version: '3'

services:
  api:
    build: .
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    container_name: standardizing_api
    volumes:
      - .:/standardizing_api
    ports:
      - "8000:8000"
    environment:
      - USE_DOCKER=yes
      - PYTHONUNBUFFERED=1
